---
services:
  piper:
    build:
      context: .
    container_name: piper 
    volumes:
      - ./models:/usr/local/piper/models
    env_file: .env  
    network_mode: host
        #    ports:
        #      - 10200:10200
    restart: unless-stopped

